#!/bin/bash -e

# ── Stage-0-Korrekturen ───────────────────────────────────────────────────────

# armhf-Architektur entfernen; auf arm64-only-System nicht benötigt
dpkg --remove-architecture armhf 2>/dev/null || true

# Kernel-Headers entfernen (~150 MB, nicht benötigt im Produktionssystem)
on_chroot << EOF
apt-get purge -y linux-headers-rpi-v8 linux-headers-rpi-2712 2>/dev/null || true
apt-get autoremove --purge -y
EOF

# ── Boot-Partition ────────────────────────────────────────────────────────────

mkdir -p "${ROOTFS_DIR}/boot/firmware"
[ -L "${ROOTFS_DIR}/boot/overlays" ] || ln -s firmware/overlays "${ROOTFS_DIR}/boot/overlays"

# cmdline.txt – console=serial0 und console=tty1 entfallen (install.sh setzt tty3)
# ROOTDEV wird von export-image/04-set-partuuid durch PARTUUID ersetzt
printf 'root=ROOTDEV rootfstype=ext4 fsck.repair=yes rootwait quiet\n' \
	> "${ROOTFS_DIR}/boot/firmware/cmdline.txt"

# config.txt – Minimalversion; wird von pigo-config/install.sh vollständig ersetzt
cat > "${ROOTFS_DIR}/boot/firmware/config.txt" << 'EOF'
auto_initramfs=1
dtoverlay=vc4-kms-v3d
disable_fw_kms_setup=1
disable_overscan=1
arm_64bit=1
arm_boost=1
[cm4]
otg_mode=1
[cm5]
dtoverlay=dwc2,dr_mode=host
[all]
EOF

# Redirect-Hinweise unter /boot/ (Kompatibilität mit alten Skripten)
for f in cmdline.txt config.txt; do
	printf 'DO NOT EDIT THIS FILE\n\nThis file has moved to /boot/firmware/%s\n' "$f" \
		> "${ROOTFS_DIR}/boot/$f"
done

# ── Basiskonfiguration ────────────────────────────────────────────────────────

cat > "${ROOTFS_DIR}/etc/fstab" << 'EOF'
proc            /proc           proc    defaults          0       0
BOOTDEV  /boot/firmware  vfat    defaults          0       2
ROOTDEV  /               ext4    defaults,noatime  0       1
EOF

echo "${TARGET_HOSTNAME}" > "${ROOTFS_DIR}/etc/hostname"
printf '127.0.1.1\t%s\n' "${TARGET_HOSTNAME}" >> "${ROOTFS_DIR}/etc/hosts"

echo "${TIMEZONE_DEFAULT}" > "${ROOTFS_DIR}/etc/timezone"
rm -f "${ROOTFS_DIR}/etc/localtime"

# /sbin-Verzeichnisse zum PATH hinzufügen (05-path.diff inline)
sed -i \
	's|PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games|PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games|g' \
	"${ROOTFS_DIR}/etc/login.defs" "${ROOTFS_DIR}/etc/profile"

# Standard-Shell für neue Benutzer auf bash setzen (01-useradd.diff inline)
sed -i 's|^SHELL=/bin/sh|SHELL=/bin/bash|'       "${ROOTFS_DIR}/etc/default/useradd"
sed -i 's|^# SKEL=/etc/skel|SKEL=/etc/skel|'    "${ROOTFS_DIR}/etc/default/useradd"

# ── Chroot-Setup ──────────────────────────────────────────────────────────────

on_chroot << EOF
# Benutzer
if ! id -u ${FIRST_USER_NAME} >/dev/null 2>&1; then
	adduser --disabled-login --gecos "" ${FIRST_USER_NAME}
fi
echo "${FIRST_USER_NAME}:${FIRST_USER_PASS}" | chpasswd
usermod -s /bin/bash ${FIRST_USER_NAME}
echo "root:root" | chpasswd
usermod --pass='*' root

# Timezone anwenden
dpkg-reconfigure -f noninteractive tzdata

# Locale sicherstellen
dpkg-reconfigure -f noninteractive locales

# Tastatur-Debconf setzen und Konsole konfigurieren
debconf-set-selections << DEBEOF
console-setup   console-setup/charmap47                      select  UTF-8
keyboard-configuration  keyboard-configuration/xkb-keymap   select  ${KEYBOARD_KEYMAP}
keyboard-configuration  keyboard-configuration/variant       select  ${KEYBOARD_LAYOUT}
keyboard-configuration  keyboard-configuration/model         select  Generic 105-key (Intl) PC
keyboard-configuration  keyboard-configuration/altgr         select  The default for the keyboard layout
keyboard-configuration  keyboard-configuration/compose       select  No compose key
DEBEOF
sed -i 's/^FONTFACE=.*/FONTFACE=""/;s/^FONTSIZE=.*/FONTSIZE=""/' /etc/default/console-setup
sed -i "s/PLACEHOLDER//"                                          /etc/default/keyboard
DEBIAN_FRONTEND=noninteractive dpkg-reconfigure keyboard-configuration console-setup

# GPIO-Gruppen
for GRP in input spi i2c gpio; do groupadd -f -r "\$GRP"; done
for GRP in adm dialout cdrom audio users sudo video games plugdev input gpio spi i2c netdev render; do
	adduser ${FIRST_USER_NAME} "\$GRP"
done

# SSH aktivieren
systemctl enable ssh

# Dateisystem-Resize beim ersten Boot
systemctl enable rpi-resize

# Predictable network names deaktivieren
SUDO_USER="${FIRST_USER_NAME}" raspi-config nonint do_net_names 1
EOF

# SSH-Host-Keys entfernen (werden beim ersten Boot neu generiert)
rm -f "${ROOTFS_DIR}/etc/ssh/ssh_host_*_key*"

# Avahi: Workstation-Discovery aktivieren
if [ -e "${ROOTFS_DIR}/etc/avahi/avahi-daemon.conf" ]; then
	sed -i 's/^#\?publish-workstation=.*/publish-workstation=yes/' \
		"${ROOTFS_DIR}/etc/avahi/avahi-daemon.conf"
fi

# Bluetooth rfkill-Whitelist (bekannte Pi-Onboard-BT-Adressen)
mkdir -p "${ROOTFS_DIR}/var/lib/systemd/rfkill/"
for addr in 107d50c000.serial 3f215040.serial 20215040.serial fe215040.serial soc; do
	echo 0 > "${ROOTFS_DIR}/var/lib/systemd/rfkill/platform-${addr}:bluetooth"
done

# ── pigo-config ───────────────────────────────────────────────────────────────

on_chroot << 'EOF'
CONFIG_DIR="/opt/pigo/pigo-config"
mkdir -p /opt/pigo
git clone "https://github.com/daviel/pigo-config" "$CONFIG_DIR"
cd "$CONFIG_DIR"
# sudo su - überspringen (bereits root im Chroot); harmlos falls install.sh bereits gefixt
grep -v '^sudo su' install.sh | bash -s
EOF
